import type { Metadata } from "next";
import "./globals.css";
import { DM_Sans } from "next/font/google";
import {ThemeProvider as NextThemesProvider} from "next-themes";
import { cookies } from "next/headers";

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-dm-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  const cookieStore = await cookies();
  const themeCookie = cookieStore.get("theme");
  const theme = themeCookie?.value || "light";

  return (
    <html lang="en" className={theme} suppressHydrationWarning>
        <body className={`${dmSans.variable} transition-[background-color,color,border-color] duration-500 bg-background text-main antialiased`}>
          <NextThemesProvider attribute="class" defaultTheme={theme} enableSystem={false}>
            {children}
          </NextThemesProvider>
      </body>
    </html>
  );
}
