import type { Metadata } from "next";
import "./globals.css";
import { DM_Sans } from "next/font/google";
import {ThemeProvider as NextThemesProvider} from "next-themes";
import { cookies } from "next/headers";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-dm-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }: Readonly<{ children: React.ReactNode; params: Promise<{ locale: string }> }>) {
  const cookieStore = await cookies();
  const themeCookie = cookieStore.get("theme");
  const theme = themeCookie?.value || "light";

  const { locale } = await params;

  if(!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang="en" className={theme} suppressHydrationWarning>
        <body className={`${dmSans.variable} transition-[background-color,color,border-color] duration-500 bg-background text-main antialiased`}>
          <NextIntlClientProvider>
            <NextThemesProvider attribute="class" defaultTheme={theme} enableSystem={false}>
              {children}
            </NextThemesProvider>
          </NextIntlClientProvider>
      </body>
    </html>
  );
}
